apiVersion: v1
kind: Service
metadata:
  name: visualization-shop-backend
  labels:
    app: visualization-shop-backend
spec:
  selector:
    app: visualization-shop-backend
  ports:
    - name: http
      port: 80
      targetPort: http
