apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: visualization-backend
  newName: us-central1-docker.pkg.dev/mirrord-test/playground-repo/visualization-backend
  newTag: d5db8756153f8f166a9e9c2f4fb81db1006b0319
- name: visualization-frontend
  newName: us-central1-docker.pkg.dev/mirrord-test/playground-repo/visualization-frontend
  newTag: d5db8756153f8f166a9e9c2f4fb81db1006b0319
