apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: visualization-shop

resources:
  - ./base/backend
  - ./base/frontend

commonLabels:
  env: playground
  team: visualization-shop
