apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace injection - forces all resources into this namespace
namespace: visualization

resources:
  - ./base/backend
  - ./base/frontend

commonLabels:
  env: playground
  team: visualization