---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ip-info.yaml
  - ip-info-grpc.yaml
  - ip-visit-consumer.yaml
  - ip-visit-counter.yaml
  - ip-visit-frontend.yaml
  - visualization-frontend.yaml
  - visualization.yaml
  - visualization-frontend.yaml
  - ip-visit-sqs-consumer.yaml
  - kafka.yaml
  - redis.yaml
