apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shop

resources:
  - ./base/infra/postgres
  - ./base/infra/kafka
  - ./base/app/inventory-service
  - ./base/app/order-service
  - ./base/app/payment-service
  - ./base/app/delivery-service
  - ./base/app/metal-mart-frontend

commonLabels:
  env: playground
  team: shop
