apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ip-visit-counter

resources:
  - ../../manifests/ip-visit

patches:
  - path: patches/image-pull-policy.yaml
    target:
      kind: Deployment
  - path: patches/nodeport-service.yaml
    target:
      kind: Service
      name: ip-visit-counter
