---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/apps
  - cluster-secret-store.yaml
  - external-secret-aws.yaml
  - external-secret-mirrord.yaml

patches:
  - path: ip-visit-counter-patch.yaml
  - path: ip-visit-sqs-consumer-patch.yaml
