apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: patch-nodeport.yaml
- path: patch-remove-backendconfig.yaml
- path: patch-remove-backendconfig-annotation.yaml
- path: patch-local-images.yaml
