apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret.yaml

helmCharts:
  - name: temporal
    repo: https://go.temporal.io/helm-charts
    version: "0.73.1"
    releaseName: temporal
    namespace: temporal
    valuesFile: temporal-values.yaml
