apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: visualization-frontend-backendconfig
spec:
  healthCheck:
    type: HTTP
    requestPath: /visualization
    port: 3000
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 5
