---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argoproj.io
spec:
  destination:
    namespace: infra
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/infrastructure
    repoURL: https://github.com/metalbear-co/playground
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false