- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: ip-visit-aws-credentials
        key: AWS_ACCESS_KEY_ID
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: ip-visit-aws-credentials
        key: AWS_SECRET_ACCESS_KEY
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: AWS_DEFAULT_REGION
    value: "eu-north-1"
- op: add
  path: "/spec/template/spec/containers/0/env/-"
  value:
    name: SQSQUEUENAME
    valueFrom:
      configMapKeyRef:
        name: ip-visit-sqs-consumer
        key: ip_count_queue
