apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- path: ip-visit-counter-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: ip-visit-counter
    version: v1
- path: ip-visit-sqs-consumer-patch.yaml
  target:
    group: apps
    kind: Deployment
    name: ip-visit-sqs-consumer
    version: v1
images:
- name: ip-visit-counter
  newName: us-central1-docker.pkg.dev/mirrord-test/playground-repo/ip-visit-counter
  newTag: bc2ab4fc4eaa1df9c8a3134eea4e79411392b025
