apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: ip-visit-counter-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: ip-visit-counter
  - path: ip-visit-sqs-consumer-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: ip-visit-sqs-consumer
