name: Build and Push

on:
  push:
    branches: [ "main", "gke-dev-playground" ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID || 'mirrord-test' }}
  REGION: us-central1
  GAR_REPO: playground-repo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        service:
          - ip-visit-counter
          - ip-visit-consumer
          - ip-visit-frontend
          - ip-visit-sqs-consumer
          - visualization-backend
          - visualization-frontend
          - ip-info

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGION }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ matrix.service }}:${{ github.sha }}

      - name: Install Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
          sudo mv kustomize /usr/local/bin/

      - name: Determine Kustomize Directory
        id: kustomize-dir
        run: |
          if [[ "${{ matrix.service }}" == "visualization-backend" ]] || [[ "${{ matrix.service }}" == "visualization-frontend" ]]; then
            echo "dir=apps/visualization/k8s/overlays/dev" >> $GITHUB_OUTPUT
            echo "file=apps/visualization/k8s/overlays/dev/kustomization.yaml" >> $GITHUB_OUTPUT
          else
            echo "dir=apps/ipvc/k8s/overlays/dev" >> $GITHUB_OUTPUT
            echo "file=apps/ipvc/k8s/overlays/dev/kustomization.yaml" >> $GITHUB_OUTPUT
          fi

      - name: Update Image Tag in Kustomize
        working-directory: ${{ steps.kustomize-dir.outputs.dir }}
        run: |
          kustomize edit set image ${{ matrix.service }}=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO }}/${{ matrix.service }}:${{ github.sha }}

      - name: Commit and Push
        uses: ./.github/actions/git-auto-commit-action
        with:
          commit_message: "chore(ci): update image tag for ${{ matrix.service }} to ${{ github.sha }}"
          file_pattern: ${{ steps.kustomize-dir.outputs.file }}
